---
- hosts: local
  roles:
    - common
    - role: python
      become: yes
      become_user: root
    - role: jupyter
      become: yes
      become_user: root
    - jupyter-config
    - role: r
      become: yes
      become_user: root
