---
- hosts: default
  roles:
    - common
    - role: python
      become: yes
      become_user: root
    - role: python-science
      become: yes
      become_user: root
    - role: jupyter
      become: yes
      become_user: root
    - role: r
      become: yes
      become_user: root
    - role: r-kernel
      become: yes
      become_user: root
    - jupyter-config
