---
- name: Build dependencies
  apt: name={{item}} state=build-dep force=yes autoremove=yes
  with_items: "{{python_build_dep}}"

- name: Install dependencies
  apt: name={{item}} state=installed update_cache=true force=yes autoremove=yes
  with_items: "{{python_science_dep}}"

- name: Install python packages
  pip: executable=pip3 name={{item}}
  with_items: "{{pip_science_packages}}"

